# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
RUN apt-get update && apt-get install -y libpq-dev gcc python3-dev
COPY requirements.txt /code/
RUN pip install -r requirements.txt
RUN playwright install chromium
COPY . /code/
