name: trist_draft_dev

services:
  django-postgres-test:
    image: postgres@sha256:f1341c01408dc7278e9d365ed4f860cd3f87dd16b4464ac326fc0f422083a579
    container_name: django-postgres-test
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - /mnt/user/docker/trist_draft/django_postgres_test:/var/lib/postgresql/data
      - /mnt/user/docker/trist_draft/draft_data:/home/draft_data
    env_file:
      - ./django-test.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 120s
      timeout: 10s
      retries: 5

  django-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-test
    restart: unless-stopped
    volumes:
      - /mnt/user/docker/trist_draft/trist_draft_dev:/code
      - /mnt/user/docker/trist_draft/draft_data:/code/draft_data
    ports:
      - "8002:8000"
    depends_on:
      - django-postgres-test
      - redis-test
    env_file:
      - ./django-test.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 120s
      timeout: 10s
      retries: 5

  redis-test:
    image: redis:5
    container_name: django_redis_test
    restart: unless-stopped
    depends_on:
      - django-postgres-test
    ports:
     - "6380:6379"
    volumes:
      - /mnt/user/docker/trist_draft/django_redis_test:/var/lib/redis
      # Fallback to local redis.conf if exists, but we probably shouldn't mount the same config 
      # file unless it's read only. However, redis doesn't modify its config.
      # Let's omit the custom redis.conf for testing unless needed.
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 120s
      timeout: 10s
      retries: 5
