# Generated by Django 3.2.11 on 2022-06-19 14:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_bidder', models.IntegerField(default=0)),
                ('bid_timer', models.IntegerField(default=0)),
                ('bid_timer_active', models.BooleanField(default=False)),
                ('highest_bid', models.IntegerField(default=0)),
                ('highest_contract_years', models.IntegerField(default=0)),
                ('team_with_highest_bid', models.IntegerField(default=0)),
                ('initiated_auction', models.IntegerField(default=0)),
                ('auction_is_rookie', models.BooleanField(default=False)),
                ('auction_is_rfa', models.BooleanField(default=False)),
                ('auction_is_ufa', models.BooleanField(default=False)),
                ('rookie_draft_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('rookie_draft_current_position', models.IntegerField(default=0)),
                ('player_for_auction_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player_for_auction_team', models.CharField(blank=True, max_length=50, null=True)),
                ('player_for_auction_position', models.CharField(blank=True, max_length=50, null=True)),
                ('auction_type', models.CharField(choices=[('rookie', 'Rookie'), ('rfa', 'Restricted Free Agent'), ('ufa', 'Unrestricted Free Agent')], default='rookie', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='drafted_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=5)),
                ('full_name', models.CharField(max_length=100)),
                ('team_drafted_by', models.CharField(default='', max_length=50)),
                ('years_drafted', models.PositiveSmallIntegerField()),
                ('contract_price', models.PositiveSmallIntegerField()),
                ('is_rookie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='nfl_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_short_name', models.CharField(max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('team_id', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('madden_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('signing_bonus', models.PositiveIntegerField(blank=True, null=True)),
                ('birthday', models.PositiveIntegerField(blank=True, null=True)),
                ('years_pro', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drafted_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='auction_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('initiated_auction', models.BooleanField(default=False)),
                ('still_in_auction', models.BooleanField(default=False)),
                ('current_bid', models.IntegerField(blank=True, default=0, null=True)),
                ('contract_years_bid', models.IntegerField(blank=True, default=0, null=True)),
                ('draft_order', models.IntegerField(default=999)),
                ('currently_bidding', models.BooleanField(default=False)),
                ('last_bid_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pass_available', models.BooleanField(default=True)),
                ('dropped_out_of_selection', models.BooleanField(default=False)),
                ('starting_budget', models.IntegerField(default=0)),
                ('budget_remaining', models.IntegerField(default=0)),
                ('initial_rfa_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('current_rfa_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('rfas_remaining', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
