# Generated by Django 3.2.11 on 2022-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0003_alter_nfl_player_drafted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_user',
            name='bathroom_mode_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
