# Generated by Django 3.2.11 on 2022-07-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0004_auction_user_bathroom_mode_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafted_player',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
