# Generated by Django 3.2.11 on 2022-07-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0005_drafted_player_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafted_player',
            name='draft_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
