# Generated by Django 3.2.11 on 2022-08-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0006_drafted_player_draft_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfl_player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='height',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='jersey_number',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='madden_score',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='signing_bonus',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='total_salary',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='nfl_player',
            name='years_pro',
        ),
    ]
