# Generated by Django 3.2.11 on 2022-08-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0007_auto_20220801_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfl_player',
            name='player_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
