# Generated by Django 3.2.20 on 2023-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0008_nfl_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_manager',
            name='initial_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction_manager',
            name='initial_bid_years',
            field=models.IntegerField(default=0),
        ),
    ]
