# Generated by Django 3.2.20 on 2023-07-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0009_auto_20230706_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_user',
            name='current_roster_size',
            field=models.IntegerField(default=0),
        ),
    ]
