# Generated by Django 3.2.20 on 2024-08-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0012_auto_20240730_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_manager',
            name='player_for_auction_bye',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
