# Generated by Django 3.2.20 on 2024-08-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0013_auction_manager_player_for_auction_bye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfl_player',
            name='bye',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
