# Generated by Django 3.2.20 on 2025-08-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_table', '0015_auto_20250720_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_user',
            name='dropped_out_of_bid_early',
            field=models.BooleanField(default=False),
        ),
    ]
